### ISSUE TITLE
余計なスタンプです

### ISSUE THREAD

**Issue by bincooo** [aethiopicuschan/ebitengine_live2d_demo#1]
はい、お願いします。
動くモデルの顔にスタンプが追加されるのはなぜですか?

<img width="252" alt="Screenshot 2024-09-04 at 07 12 43" src="https://github.com/user-attachments/assets/d33235c8-ea3e-41ed-90ab-d45c65082dc5">

**Comment by aethiopicuschan** [comment]
issueありがとうございます。
多分なんらかのフラグの処理が抜けているのかな〜と思いますが、モデルのデータが無いと正確な原因がわからないかもしれません...。
もしくは、[cubism-go](https://github.com/aethiopicuschan/cubism-go)を使うと改善される可能性があります。

**Comment by bincooo** [comment]
Mao/Markモデルもそうですが、`cubism-go`を使ってこれも出てきます。

**Comment by aethiopicuschan** [comment]
フィードバックありがとうございます。Mao/Markモデルでcubism-goを使っても同様の症状が出るのですね。調査します。

**Comment by aethiopicuschan** [comment]
@bincooo 
`cubism-go` において原因の特定を行い、以下のPRで修正を行いました。

- https://github.com/aethiopicuschan/cubism-go/pull/46

同時に `v0.0.2` としてリリースを行いましたので `go get -u github.com/aethiopicuschan/cubism-go` で最新版の `cubism-go` を試してみてください。

問題が解決していれば、こちらのissueは閉じます。

対応が遅くなり申し訳ありません。動作確認の連絡をお待ちしております。

**Comment by bincooo** [comment]
@aethiopicuschan 
はい、効きました。感謝します

**Comment by aethiopicuschan** [comment]
ありがとうございます！またなにかありましたらお気軽にissue立てるなり連絡いただくなりしていただけると幸いです。
